apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_layout
spec:
  selector:
    matchLabels:
      app: flask_layout
  template:
    metadata:
      labels:
        app: flask_layout
    spec:
      containers:
      - image: virusker/flask_layout:latest
        name: flask_layout

---

apiVersion: v1
kind: Service
metadata:
  name: flask_layout
spec:
  type: ClusterIP
  ports:
  - name: "flask_layout"
    port: 8080
  selector:
    app: flask_layout

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask_layout
  annotations:
    dev.okteto.com/generate-host: flask_layout
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: flask_layout
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific